[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
rate_limiter = "HzcpN3BLJ19g1M12kMAuragRcQX9AmPMbFZt6VqqdiTr"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/devnet-wallet.json"

[scripts]
test = "yarn run mocha -t 1000000 tests/"
